data/manual/Plugins/Task_List.txt
My editor is set for spaces not tabs, if this messes up Zim, let me know.
=> proofing Task_List.txt

.editorconfig
Using EditorConfig makes contributing and enforcing the style guidelines easier.
http://editorconfig.org/
=> Add EditorConfig file to match style guidelines.

HACKING/Working_with_Git.txt
A couple of leftover replacements of Bazaar with Git.
=> Hacking guide update about migration to GitHub

tests/pageview.py, zim/gui/pageview.py
Fix bug #634 and add testReplaceSelection test case
=> Fix NameError in PageView.replace_selection (bug #634)

zim/applications.py
Flatpak application does not see real host command. Host command
can be executed only through D-Bus. But the interface is
asynchronous. We use the 'flatpak-spawn' utility to call host
command synchronously.
Fixes #686
=> In Flatpak use flatpak-spawn to call host command if possible.

tools/create_large_test_notebook.py
Make zim-desktop-wiki/tools/create_large_test_notebook.py work with python 3
=> Convert large notebook script to python3

data/manual/Help/Properties.txt
This feature was removed in 4ff52e2743 so changing manual accordingly.
=> Remove configuration profiles feature from manual

setup.py
Fix newline character typo (\m should be \n) in setup.py
=> Fix newline

PLUGIN_WRITING.md
update to find_extension, also include where to find it.
=> PLUGIN_WRITING: get_extensions is find_extension

data/manual/Help/Config_Files.txt, tests/www.py, zim/gui/server.py, zim/www.py
In the webserver window there is now an option for setting username and password, which are queried by the browser before you can access the hosted webpages.
=> Authentication in webservermode

CHANGELOG.md, zim/plugins/tags.py
Corrected my Name in all instances. Not sure if this is usual practice, but seems sensible to me.
=> Changed my name after marriage

data/manual/Help/Config_Files.txt
Clarified a few sections and added an example file
**No code change**
=> Partial rewrite of Help/Config_Files.txt

zim/fs.py
=> Give temporary directories unique names

data/manual/Plugins.txt, data/manual/Plugins/macOS_Menubar.txt, zim.py, zim/gui/uiactions.py, zim/main/__init__.py, zim/plugins/osx_menubar.py
Update the macOS Menubar plugin for the current version of Zim.
=> Macos integration

zim/plugins/sourceview.py
Fix #932 and a typo in sourceview.py.
=> Fix export issue and a typo in Plugin sourceview

data/manual/Plugins/Equation_Editor.txt, data/templates/plugins/equationeditor.tex, zim/plugins/equationeditor.py
=> Dark mode for equations

CONTRIBUTING.md
Fix typos, and go beyond that to elaborate some points. E.g., implementing
a new feature is one-time job, while maintaining it a long-term process, so
that what may be the hard part. Writing tests, while boring, is in the
ultimate interest of Zim users themselves, etc., etc.
Signed-off-by: Paul Sokolovsky <pfalcon@users.sourceforge.net>
=> CONTRIBUTING: Typo fixes, clarity improvements

website/pages/contribute.txt
Signed-off-by: Paul Sokolovsky <pfalcon@users.sourceforge.net>
=> website/pages/contribute.txt: Typo fix: whish -> wish

data/manual/Help/Notebooks.txt
'were' was change to 'where'
and 'some' was change to 'same'
=> fix spelling error

data/manual/About.txt
Replace CVS with Git, as most new users are hopefully not aware of CVS.
Also, emphasize that Makefile should be custom (imagine users who don't
know what Makefile is, they may get impression that Makefile is a magic
thing which compiles notes into webpage, give them at least a hint that
it should be their own magic).
Signed-off-by: Paul Sokolovsky <pfalcon@users.sourceforge.net>
=> manual/About: Typo fix and elaborate refs to VCS/Makefile

data/manual/Usage/Getting_Started.txt
=> Improved grammar

tests/pageview.py, zim/gui/pageview/__init__.py
=> Don't replace existing bullets with numbered bullets

README.md
With my previous PR I totally overlooked to update the repository's readme. This will be taken care of with this PR.
I have also included a second commit to fix problems reported by my markdown linter. I can drop that commit if this is unwanted.
Also I'd like your thoughts on the following, since updating website and readme the way I'm doing does change "the message we're sending":
- I've replaced the instructions for Homebrew and MacPorts with links to the instructions that they offer themselves. This way we don't have to maintain the specific instructions and/or keep up with their development. AFAIK, noone from our end is involved over there (please correct me if I'm wrong) and I am not going to support Zim installed via Homebrew or MacPorts either, I have my hands full.
- I also intend …
=> Update readme for macOS

data/symbols.list
=> Add box drawing characters to symbols

zim/plugins/linesorter.py
As recommended [here](https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/1040#issuecomment-607375906)
=> Update description of Line Sorter plugin

data/manual/Help/Templates.txt
Fixes #948 and thus prevents many headaches.
=> [Documentation] Fix #948; s/TRUE/True/g

zim/notebook/index/links.py, zim/notebook/index/pages.py, zim/notebook/page.py
Merging a small initial amount of type hints should expose whether they somehow break eg. Python 3.6 or PyDoctor before we go all out with automated tooling :)
* zim.notebook.index.links
- comment -> docstring
- type annotated IndexLink
* zim.notebook.index.pages
- type annotated PagesView
* zim.notebook.page
- type annotated Path, HRef, shortest_unique_names
- improved HRef documentation based on #1847
=> Some type hints and documentation improvements

website/pages/downloads.txt
built ^& tested -> built and tested
=> Fix typo in downloads.txt

data/manual/Help/Config_Files.txt, tests/pageview.py, zim/gui/pageview/__init__.py
Huge thanks to @lazka for making the PyGObject API docs available [online](https://lazka.github.io/pgi-docs/Gtk-3.0/enums.html#Gtk.Justification)!
=> Fix justification, prevent its regression, update manual. Closes #849

zim/gui/applications.py, zim/gui/pageview/__init__.py, zim/gui/preferencesdialog.py
* make pageview use zim.gui.applications.open_folder_prompt_create
* add preference to always create missing directories without prompting
* Fixes #1541
=> Feature: Option to always create non-existing folders without prompting the user

zim/gui/pageview/__init__.py
- Add toggle for the "Prefer short link names for pages" option,
shared with the Insert/Edit Link dialog. Closes #1964.
- Save selection bounds on initialization. Fixes #1963.
=> Move Selected Text: add preference for short links, bound saving.

windows/build.sh, windows/src/zim-installer.nsi
Fixes the deployment which failed due to upstream changes, and adds DisplayVersion to support updates via winget (see #2077).
=> Windows deployment changes

zim/main/__init__.py
=> Catch plugin not having command class

data/manual/Plugins/Link_Map.txt, zim/plugins/linkmap.py
See the manual for more information.
=> LinkMap: add refresh button, opening links in new windows & preferences for zoom and link opening

data/manual/Plugins.txt, data/manual/Plugins/WindowTitleEditor.txt, tests/__init__.py, tests/windowtitleeditor.py, zim/plugins/windowtitleeditor.py
=> Add Window Title Editor plugin

data/manual/Help/Preferences.txt, zim/gui/pageview/__init__.py
=> Add option to disable link overlay labels
