zim-desktop-wiki/zim-desktop-wiki

- website/pages/downloads.txt
"Fedora extras" is long gone.
Add an url to easily find the package in Fedora's infrastructure.
> Update hint to Fedora

- zim/gui/mainwindow.py
- zim/gui/widgets.py
Also remove comment about resize grip which has been removed from Gtk.Statusbar.
Resize grips have resided in Gtk.Window but have been removed there too in the
mean time.
> MainWindow: Remove unnecessary layer of HBox

- setup.py
- xdg/org.zim_wiki.Zim.metainfo.xml
Hyphens are discouraged to be used with respect to recent version of AppStream,
and 'org.zim-wiki.Zim' failed to be a valid Flatpak ID.
> Change metainfo ID to 'org.zim_wiki.Zim'

- zim/formats/plain.py
`zim/formats/plain.py` it looks like it was started and unfinished
fix https://github.com/jaap-karssenberg/zim-desktop-wiki/issues/295
> fix #295 indent in dump_list

- zim/plugins/attachmentbrowser/filebrowser.py
We might be watching the wrong folder, but sometimes we are alerted to folder changes when our folder does not exist.
```
ERROR: Exception in signal handler for changed on <zim.newfs.helpers.FSObjectMonitor object at 0x7fb2a4cd2a90>
Traceback (most recent call last):
File "zim/signals.py", line 338, in emit
r = handler(self, *args)
File "zim/plugins/attachmentbrowser/filebrowser.py", line 294, in _on_folder_changed
changed = self.folder and self.folder.mtime() != self._mtime
File "zim/newfs/local.py", line 70, in mtime
return self._stat().st_mtime
File "zim/newfs/local.py", line 54, in _stat
raise FileNotFoundError(self)
FileNotFoundError: No such file or folder...
```
> FileNotFoundError: No such file or folder

- zim/plugins/bookmarksbar.py
gtk3 Requisition does dot support indexing, use `.width` instead to get button's width.
> Fix #625 : no right-click on bookmark button

- zim/gui/pageview.py
A small typo in the code causes the "Edit Image" dialog crashing
on "OK" button click. This happens when the field "Link to" on
the dialog is set to a file name.
This simple patch will fix the problem.
> Fix crash in Edit Image dialog when "Link to" set to a file.

- data/manual/Plugins/Journal.txt
Hopefully will help avoid confusion like in #737
> Update manual to depict calendar plugin renaming

- .editorconfig
- CONTRIBUTING.md
- data/manual/FAQ.txt
- data/manual/Help/Default_Applications.txt
- data/manual/Help/Export/HTML.txt
- data/manual/Help/Importing_external_files.txt
- data/manual/Plugins/Equation_Editor.txt
- data/manual/Plugins/Version_Control.txt
- data/symbols.list
- data/urls.list
- debian/control
- tests/notebook.py
- tests/pageview.py
- website/pages/contribute.txt
- website/pages/downloads.txt
- windows/src/help.html
- zim/__init__.py
- zim/gui/preferencesdialog.py
- zim/gui/templateeditordialog.py
Replaced with https:// http:// links which redirect to https:// anyway
(Only in places which seemed safe to do this replacement)
Used following script to find such links:
```bash
#!/bin/bash
IFS= readarray -d '' FILES < <(git --no-pager grep --null -l http:// ":(exclude)*svg")
for FILE in "${FILES[@]}"; do 
echo "$FILE"
sed -i 's|http://www.zim-wiki.org|https://www.zim-wiki.org|' "$FILE"
for URL in $(grep --extended-regexp --only-matching 'http://[^| ]*[^.|]' "$FILE"); do
HTTPS_URL="https:${URL#http:}"
REDIRECT_URL=$(curl --max-time 5 -L --head --output /dev/null --silent --write-out '%{url_effective}' "$URL")
if [[ "$REDIRECT_URL" == "$HTTPS_URL"* ]]; then
sed -i "s|${URL}|${HTTPS_URL}|" "$FILE"
fi
echo "$URL -> $REDIRECT_URL"
done
git add -p "$FILE"
done
```
> Replace auto redirecting http:// with https://

- data/templates/rst/Default.rst
The overlines and underlines for page titles were not long enough sometimes when exporting in reStructuredText format. I made the overline and underline lengths depend on the title length by updating the Default.rst template.
> Fixed the title in rst default template

- zim/plugins/screenshot.py
The existing screenshot commands (import, scrot) do not work properly
on all systems (artifacts).
> Add gnome-screenshot to screenshot plugin.

- data/manual/Plugins/Task_List.txt
- zim/plugins/tasklist/__init__.py
- zim/plugins/tasklist/gui.py
For my personal task list workflow both priority and due date are essential properties, hence I need the ability to sort after either of these in the side pane view. Maybe that is appropriate and worthy to be included into zim in general.
This discontinues the TODO comment to split the different views of the task list into different classes: different column layouts can be specified by an explicit enum parameter.
This pull request is the python3/gtk3 successor of a now withdrawn pull request for python2/gtk2.
I am open to criticism and would contribute a German translation after merge.
> Task list: setting to display due date in sidepane view.

- zim/plugins/sourceview.py
Configurable, by default it is is same as it has been, linenumbers are visible. This affects behaviour for newly created blocks. After it has been created, line numbers can be displayed or hidden, just as it has been poissible until now. 
There are currently no tests - I can write some if you want and explain me basic logic of manipulating tree. 
My idea is to create codeblock, check linenumbers, change setting and create new codeblock. 
I was looking into it and don't understand how `tree.find('object')` works, and after calling action.activate for the second time, tree (tried `print(tree.tostring())`) doesn't appear to change.
> Sourceview: setting to have linenumbers off for newly created items.

- data/manual/Help/Config_Files.txt
Included specific and working CSS examples (for ~/.config/gtk-3.0/gtk.css)
> Documentation: more details and examples on how to customize Zim's appearence in GTK3

- tests/notebook.py
- zim/notebook/notebook.py
When the name of a non-existent page is changed, the pages that link to this non-existent page don't get updated.
Also fixes moving of non-existent pages.
> fixes handling of non-existent pages

- zim/plugins/distractionfree.py
The box colors are set to the same value as the background color for true distraction free editing.
Regular view: 
Distraction free before:
Distraction free after patch:
> distraction free editing plugin: remove all colors of the window chrome 

- zim/__init__.py
Allow an environment variable named `TEXTDOMAINDIR` to set the locale directory if we're not running inside the source directory. This allows the macOS application bundle to set the locale directory to a location inside the bundle itself.
Full disclosure: I've read the contribution guidelines and I admit I have not written nor am I planning to write a test for this. (My plan is to familiarize myself with that at a later date.) If this disqualifies this PR from being merged, that'll be on me.
> Evaluate TEXTDOMAINDIR to set locale directory

- zim/gui/pageview.py
This makes the find bar behaviour match other common applications.
* When a match is found don't defocus the find bar.
* Press Ctrl+G or Enter to go to next occurence.
* If Ctrl+F is pressed and there is already text inside the find bar then the text is highlighed (even if it is already visible).
Also fixes launchpad bugs:
https://bugs.launchpad.net/zim/+bug/1036821
https://bugs.launchpad.net/zim/+bug/1589085
https://bugs.launchpad.net/zim/+bug/1685371
> Improve find bar behaviour (fixes #317 and #128)

- zim/gui/pageview.py
Changes the order of the format box and calendar widget in the Insert Date and Time dialog for better user experience. See #795
> Swap order of the format and calendar panels

- CHANGELOG.md
- data/manual/Help/Wiki_Syntax.txt
- tests/data/formats/export.html
- tests/data/formats/export.markdown
- tests/data/formats/export.rst
- tests/data/formats/export.tex
- tests/data/formats/parsetree.xml
- tests/data/formats/plain.txt
- tests/data/formats/wiki.txt
- tests/formats.py
- tests/pageview.py
- zim/formats/__init__.py
- zim/formats/wiki.py
- zim/gui/mainwindow.py
- zim/gui/pageview.py
- zim/parser.py
Finally it is possible to apply multiple text styles to a text. Ex: Links can be nested under a striked text and still be clickable.
> For testing what I had in mind is to test also the export formats (html / latex / ...) handle nested tags well. 
Okay, implemented, `./test.py formats` works perfectly!
> Documentation wise, I think this should land somewhere in the manual.
Added to the docs!
(This is a reopening of #468 that was closed probably by mistake when changing the Gtk3 branch from `next` to `master`.)
> multiformatting! FIX #305

- zim/plugins/base/imagegenerator.py
In 27c96ef, all 'logfile' should be renamed to 'log_file'. But
there are missing ones.
Fixes #1110
> Missed renaming of some occurrences of 'logfile'.

- zim/gui/preferencesdialog.py
- zim/gui/propertiesdialog.py
Since it is little bit confusing the user has to close the Plugins tab and open `File / Properties` to see all options of some plugins, `Edit / Preferences / Plugins / Properties` button has been added
> Plugins tab Properties button

- zim/formats/__init__.py
This change is similar to feba6b2cf2b23c4c019a7bc770da44064cc6dd42 and fixes error described in https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/1212#issuecomment-694513278
> Fix reading preformatted text under Python 3.9

- zim/plugins/osx_menubar.py
This PR fixes the following warning:
> WARNING: Zim.app/Contents/Resources/lib/python3.8/site-packages/zim/plugins/osx_menubar.py:31: PyGIWarning: GtkosxApplication was imported without specifying a version first. Use gi.require_version('GtkosxApplication', '1.0') before import to ensure that the right version gets loaded.
> from gi.repository import GtkosxApplication
> Fix warning about not having called gi.require_version

- README.md
By explicitly elaborating the XDG path setup for people launching their
zim in a Python virtual environment, we will help them to launch their
zim easier without confusion.
Closes #1381
> Update README for XDG paths when using Python virtual environment

- tests/__init__.py
- tests/newfs.py
- tests/uiactions.py
Changes to the test suite that make it run successfully in Fedora build environment. The changes are not specific to Fedora, they may help getting the tests run in other build environments as well.
Issues fixed:
1. Do not expect home directory to be of format `/home/user` - it can also be a single path directory like `/builddir`.
2. Specify `XDG_RUNTIME_DIR` environment variable during test initialization. It is not always set in headless environments.
3. Allow addition of `file://`prefix to filenames in some `uiactions` tests, because Zim does this when the files are opened with the embedded WebBrowser application. This happens in Fedora build environment, presumably because no applications for opening files have been defined there. (I admit I do not understand the prefix adding part …
> Make test suite run in Fedora build environment

- .gitignore
- zim/notebook/notebook.py
This makes the "shared" config option describe in [https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/master/data/manual/Help/Config_Files.txt](https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/master/data/manual/Help/Config_Files.txt) work again when shared is set to false.
The `_iswritable` function always returned false since the call to `f.remove(cleanup=False)` failed because the function doesn't take any parameters. I also added code to create the .zim folder which the state and index file should be located in when shared is set to false.
I added an entry to the gitignore file for files associated with the PyCharm IDE which I use for development. I think it makes since to include it since it's a popular Python IDE.
Fixes #1049.
> Fix shared config option (fixes #1049)

- README.md
- added in 13d8c46b (I thought it might be a footnote or similar, but there isn't one)
- not present in the develop branch where 13d8c46b isn't merged
Two questions for maintainers:
- For the record, are this kind of small fixes worthy of PRs or should I gather up a few? I consider this one to be due to its visibility.
- As I skimmed the README for other stray markup, I noticed data/{urls,symbols}.list aren't listed under files included from other sources. Should they be?
> Remove trailing **** from first paragraph

- PLUGIN_WRITING.md
Also removed extraneous tabs: makes it easier to copy.
> Missing comma in plugin skeleton

- setup.py
- do not ship a mime icon for very old GNOME versions
- do not install the application icon in the legacy `/usr/share/pixmaps` location
> Stop installing legacy icons or icons in legacy locations

- zim/gui/pageview/__init__.py
This fixes that by resetting the dimensions after path changes if the width of the image is 1.
Steps to reproduce:
1. Edit image properties, set a custom width and press OK; the width changes
2. Edit image properties, change Location to a nonexistent one and press OK;  the image is replaced with a placeholder
3. Edit image properties and correct the Location; notice that the width is set to 1
4. Press OK; the image is now 1 pixel wide
A better alternative would be restoring the previously set dimensions, but let's not make perfect the enemy of good.
> Fix images becoming one pixel wide after fixing path

- windows/src/zim.spec
> Windows build: fix missing icon in font chooser dialog

- data/manual/Help/Menu_Items.txt
- tests/mainwindow.py
- zim/gui/mainwindow.py
- zim/gui/uiactions.py
Add test to ensure all menu items a documented in manual.
Over the time new menu items were inserted, some of them move to different menus or default key bindings were changed. This PR updates the [manual page on menu items](https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/master/data/manual/Help/Menu_Items.txt) to the current development state and adds a simple test to make sure that all menu items are documented so that it'll be harder to forget to update the manual when new features are being introduced (the test doesn't consider plugin menu items).
> Update manual page on menu items

- zim/gui/pageview/__init__.py
The new docstring follows the style of the other menu actions' docstrings (and doesn't confuse my tab-native docstring parser by indenting with spaces).
@jaap-karssenberg a few questions about a possible tool related to #155 :
1. `"""` vs. `'''`? PEP 257 says to use the former, while zim-desktop-wiki has a few thousand `'''`s with a couple hundred `"""`s mixed in.
- Should one be standardized?
2. Line width; PEP 257 says 72, while Zim's docstrings max out at well over a hundred chars. I've prototyped a solution using TextWrapper that errs on the side of caution to not break code blocks etc, but judging whether the first line should stand alone is next to impossible due to incorrect formatting.
- Should all docstrings be rewrapped and to what width?
3. Indentation inside docstrings; sphinx …
> Update insert_line documentation

- data/manual/Help/Menu_Items.txt
- tests/mainwindow.py
Fix wrong accel key label introduced in menu items help page in commit 9dfd96afc.
I'm very sorry but I overlooked this mistake in #1502.
> Fix zoom-in accelerator label

- data/manual/FAQ.txt
and make link captions consistent throughout the page (name only without path)
> Fix typo in FAQ manual page

- zim/gui/pageview/__init__.py
Returns the "link" arg instead. To reproduce bug: Ctrl+L on a link to a nonexistent anchor.
> InsertLinkDialog._link_to_text: fix IndexError when len(href.parts()) == 0

- zim/plugins/backlinkpane.py
backlinks plugin: fixed "Open in new page" popup entry that is currently not shown when trying to open the context menu
> fixing backlinks plugin: open backlink in new window

- zim/gui/pageview/__init__.py
Changed the scope of the check, now only escapes selected text
> FindWidget: re.escape only selected text; fixes #1566

- data/manual/Help/Links.txt
Currently, the docs refer to a html:// page, probably http:// or https:// was ment.
> Fix html:// to https:// in Link manual page

- data/manual/Plugins/Log_events_with_Zeitgeist.txt
- zim/plugins/zeitgeist-logger.py
Some minimal changes to make the zeitgeist plugin work again. Note that this now requires the `python3-zeitgeist` package on Debian/Ubuntu.
Fixes #787
> Make zeitgeist plugin work again

- zim/plugins/zeitgeist-logger.py
Apologies for proposing another PR for the zeitgeist plugin after #1625, but as @Nick222 reported in #1640, its current state is quite broken... This PR should fix the following two problems in the zeitgeist plugin:
* modify and delete events for not sent correctly at all (not sure whether this was always broken or resulted from changes in zim)
* send an access event for the page that is open when starting zim (the plugin is loaded after its page-opened event).
Fixes #1640
> Zeitgeist plugin fixes

- zim/plugins/journal.py
If I open the journal entry from the command line (e.g. `zim notes Journal:2021:11:07`) the date shown in the journal selector is always today, regardless of the actual date opened. This patch attempts to rectify the issue by setting the page in the calendar widget right after initialization.
> set initial date for the journal widget if opening journal page from CLI

- zim/gui/pageview/__init__.py
The placement follows that of normal cut and copy, while the mnemonic is 'k' to avoid collisions.
Use case: Reorganizing link lists
Examples:
1. Turning links with "and" in them into two separate links
2. Keeping the link text while moving the link to a sub-item
> Feature: Add "Cut Link" to context menu

- tests/applications.py
- zim/gui/applications.py
The [specification](https://specifications.freedesktop.org/mime-apps-spec/latest/ar01s02.html) states the desktop name should looked up in lowercase form.
This is related to issue #1531.
> Use lowercase desktop name when looking up desktop specific mimeapps.list file

- data/symbols.list
Should probs look into what other symbols are missing - what's 8758 for
example?
Fixes #1153.
> symbol.list: add 8757 (because)

- zim/plugins/pathbar.py
Moves call to shortest_unique_names into a new _get_labels method
of the PathBar class that's overriden by PATHBAR_PATH to avoid
eg. the path to the Jounal page of every nth day of the nth month
looking weird. Fixes #1804.
> Don't make PATHBAR_PATH labels unique. Fixes #1804

- tests/imagegenerators.py
- tests/tableeditor.py
assertEquals is deprecated in Python 3.2 and removed in 3.11.
> Use assertEqual instead of assertEquals

- zim/notebook/notebook.py
`NotebookInfo` was not defined in `notebook.py`. It's imported here to avoid circular imports and also because this property doesn't seem to be used by any existing code - I bumped into this while trying to port the patch from #64 to the latest version.
Let me know if you want a test for this - imo this should be covered by a test of a feature which requires this property
> Fix NameError raised by self.notebook.info

- .github/workflows/test.yml
until #1797 is fixed. This makes the check-marks actually useful for catching failing tests in the meantime.
> Disable automatic tests on Mac OS

- README.md
- debian/control
- setup.py
- zim.py
- zim/config/dicts.py
- zim/plugins/__init__.py
- zim/templates/expression.py
- zim/templates/processor.py
Needed for type hints etc; 3.5 has been EOL for over a year, [the oldest Ubuntu LTS is on 3.6](https://packages.ubuntu.com/search?keywords=python3).
Previously discussed at #1776.
Includes the slightest bit of cleanup of old code, didn't touch eg. the regex patterns that have been held back by Python 2.5 (not a typo!).
Let's start a happy new year with a new(er) Python version! :)
> Upgrade Python version requirement to >= 3.6

- .github/workflows/test.yml
We're not doing any inbetween-version-spesific stuff, so stick to the oldest and newest versions on dev branch
> Optimize testing

- makeman.py
The description section of the man page is extracted from the README.md file.
This extraction does not handle markdown lists properly. As a result the list
of use cases is not displayed aesthetically.
Zim can be used to:
* Keep an archive of notes * Keep a daily or weekly journal * Take  notes
during  meetings  or  lectures * Organize task lists * Draft blog entries
and emails * Do brainstorming
This change update the formatting of this list like:
Zim can be used to:
•      Keep an archive of notes
•      Keep a daily or weekly journal
•      Take notes during meetings or lectures
•      Organize task lists
•      Draft blog entries and emails
•      Do brainstorming
> Improve man page to correctly display Zim use cases.

- zim/plugins/sourceview.py
Fixes #1921
Ref: https://lazka.github.io/pgi-docs/GtkSource-3.0/classes/Language.html#GtkSource.Language.get_hidden
> Source View plugin: Don't show hidden languages

- data/manual/Plugins/Score_Editor.txt
- zim/plugins/scoreeditor.py
On Windows, users may have the lilypond executable in their path
while lacking convert-ly. This adds a check for the availability
of the latter to prevent activating the plugin while lacking the
required dependencies.
Closes #1923
> Score editor: add check for convert-ly

- tests/clipboard.py
- tests/uiactions.py
- zim/gui/clipboard.py
- zim/gui/pageview/__init__.py
- zim/notebook/index/links.py
- zim/notebook/notebook.py
- zim/notebook/page.py
* Add HRef.short_name method, which returns the last name part and/or anchor if any (by @roland-ruedenauer) Fixes #1769.
* Add sanity checks for usage of HRef.parts(). Fixes #1929.
* Adds tests to prevent the above from regressing
> HRef short_name & anchor link fixes for #1769 & #1929

- tests/tokenparser.py
- zim/formats/__init__.py
- zim/plugins/tableofcontents.py
- zim/plugins/tasklist/indexer.py
- zim/tokenparser.py
Taken from zim-desktop-wiki/zim-desktop-wiki#1560 by @roland-ruedenauer 
* s/collect_untill_end_token_iter/collect_until_end_token_iter/g
* filter_token:
Iterator returning all tokens occurring before detecting
a closing tag for 'end_token'.
Nested occurrence of 'end_token' is taken into account.
> Token parsing: fix typo, add filter_token

- tests/tableofcontents.py
- zim/gui/pageview/__init__.py
- zim/plugins/tableofcontents.py
Based on #1560, doesn't include the anchor stuff.
Add linking related UX to ToC pane                                                                                                               
Extend ToC pane context menu with                                                                                                                
* "Copy link to heading"                                                                                                                         
* "Open in New Window"                                                                                                                           
Also fixes #1730 and horizontal divider                                                                                                          
context menu …
> Add linking related UX to ToC pane

- .github/workflows/test.yml
This PR adds testing for macOS based on the same (JHBuild based) dependencies that I use to create our app.  
Fixes https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/1797
- Due to its very different nature I decided to create a dedicated job instead of complicating the neat matrix setup (I'm open to other opinions).
- The job is named "Python 3.x" as the Python version cannot be chosen from the outside and is unknown from the job's perspective.
- The tests need to be run on `macos-10.15`. `macos-latest` (i.e. `macos-11`) causes problems.
- I renamed the job from `build` to `test` as I assume that is a copy-paste mistake. While I usually refrain from making changes outside of my feature, I did this for uniformity as I wasn't going to name my new test job `build_macos`. 
- This PR …
> Run tests on macOS using custom dependencies

- .github/workflows/test.yml
The links in our CI need updating to accommodate changes in the upstream project that provides the precompiled dependencies to run the test suite on macOS. Downloads are now architecture-specific.
> Fix macOS CI: add architecture to dependencies

- website/pages/downloads.txt
Update the download page of the website by removing the notice about Rosetta 2. We have a native macOS arm64 release now and no longer require this.
I've opened this PR against `master` instead of `develop` as it does not depend on or interfere with current development or release cycles. The arm64 version is available as of now.
> Website: remove notice about Rosetta 2

- zim/search.py
The logging message invocation in the exception handler referenced a non-existing variable and hence made exception handling itself crash.
This replaces PR https://github.com/zim-desktop-wiki/zim-desktop-wiki/pull/2037.
> Corrected variable name.

- zim/plugins/versioncontrol/__init__.py
- zim/plugins/versioncontrol/fossil.py
- add '--keep' flag to fossil open, fixes #2005
- check for 'notebook.fossil', fixes #2006
- fix typo in function call, fixes #1248
I've confirmed that creating a new fossil repository and saving versions both work; `fossil timeline` lists all non-empty commits created from Zim, and the saving GUI correctly lists edited files.
> Version control: fix fossil

- zim/plugins/base/imagegenerator.py
Add check to make closing the window via other means act
identically to pressing the "Cancel" button. Fixes #2081.
> Allow cancelling ImageGeneratorDialog via esc

- zim/gui/pageview/__init__.py
I found no way to close the "find bar" opened by a search operation using the keyboard, so I added a small keypress handler a while ago that allows one to close the "find bar" via pressing the ESC key.
So far I've only tested this on Linux.
> Support closing an open 'find bar' by pressing ESC

- data/symbols.list
Currently, the `Insert Symbol` plugin autoformats `--` to `—` (em dash). This is counter-intuitive since `--` usually represents `–` (en dashes) and `---` represents `—` (em dashes) in other markups such as LaTeX.
This pull request changes the default behavior as discussed in #1419.
> Enables distinct shortcuts for en and em dashes

- data/manual/Help/Templates.txt
Added an example showing how to reference a template resource using the `resource(filename)` function. It wasn't clear to me that the filename should be within quotes. Also fixed a typo and some formatting.
> Fixes typo and adds example to Template manual

- data/manual/Help/Menu_Items.txt
- zim/gui/pageview/__init__.py
- zim/gui/uiactions.py
- zim/plugins/pageindex/__init__.py
Most menu items are written in Title Case, except for a few. I changed these to Title Case for consistency. Example: `View debug log` to `View Debug Log`.
> Standardize menu items to title case

- zim/main/__init__.py
Present in `data/manual/Help/Commandline_Options.txt`
See also https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/2089#issuecomment-1190460461
> Add/restore mention of --index [OPTIONS] in usage

- .github/workflows/test.yml
This PR improves the test job for macOS to take advantage of recent enhancements of the GitLab CI we use to build the macOS app.
> Update test job for macOS

- zim/config/dicts.py
The fix for Python Issue BPO-27275 changes `OrderedDict.pop()` behavior
so that it does not call `__delitem__` any more.
On the other hand, `ControlledDict` expects such call to happen
to emit the `changed`' event.
Fixed by overriding `pop()` in `ControlledDict`
so that it explictly emits `changed`.
Fixes #2087
> Fix ControlledDict.pop on Python 3.11

- tests/pageview.py
- zim/gui/pageview/__init__.py
Status: https://github.com/zim-desktop-wiki/zim-desktop-wiki/pull/1534#issuecomment-986004627
---
Usually I don't want my empty lines to become empty list members, eg.
```
this is a list where items are separated by an empty line
let's make it into a checklist!
```
would turn into
```
[ ] this is a list where items are separated by an empty line
[ ] 
[ ] let's make it into a checklist!
```
instead of (imo) the more sane
```
[ ] this is a list where items are separated by an empty line
[ ] let's make it into a checklist!
```
Thus, this change. Q&A:
* Does it break some other functionality?
* Maybe. It didn't break any tests though could do with some of its own.
* Shouldn't the empty lines be removed?
* No, some people might be into that sort of stuff and it's not up to us to judge them.
* …
> foreach_line_in_selection: ignore empty lines

- zim/plugins/pageindex/__init__.py
Fixes a bug where some users could no longer roll/unroll a currently selected page.
This was due to autoexpand/autocollapse being called on the currently selected page whenever the roll/unroll toggle was clicked.
#1820 - The "And another one" example.
> Fix roll/unroll issue on currently selected page in treeview.

- tests/pageview.py
- zim/gui/pageview/__init__.py
`/^* /` would produce a bullet while the verbatim format was active.
Source text produced before this PR after selecting the verbatim formatting and typing `* test`:
`* test` (the bullet gets autoformatted and the verbatim format gets ditched)
New behavior:
`''* test''` (text typed in verbatim is displayed verbatim)
> Prevent autoformatting of bullets during verbatim

- zim/gui/insertedobjects.py
- zim/plugins/base/imagegenerator.py
Regenerates missing images on page open/reload and when opening or accepting the `ImageGeneratorDialog`. Outdated images are also regenerated on page open/reload (ie. on the initialization of `BackwardImageGeneratorModel`) based on `LocalFile.mtime()`, allowing tighter workflows using external editors (eg. `vimdot` for diagrams, or any Lilypond-compatible editor for sheet music etc).
Due to the existing implementation writing the script file **after** generating the image, `LocalFile._set_mtime()` is called and thus
depended upon.
Neither missing nor outdated images are regenerated on export.
Partially fixes #2102.
Also includes a nicer fallback for missing images (should both the source file and the render go missing):
> Bettering the handling of missing images re: #2102

- tests/data/formats/export.markdown
- zim/formats/markdown.py
Pandoc does support [setting image dimensions and ID](https://github.com/jgm/pandoc/issues/261).
This patch implements the syntax inside the markdown exporter.
> Include image dimensions and ID in markdown
